# Generated by Django 4.1.3 on 2024-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('passenger_name', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='station',
        ),
        migrations.RemoveField(
            model_name='route',
            name='train',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
