# Generated by Django 4.1.3 on 2024-04-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_remove_route_station_remove_route_train_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainTitle', models.CharField(max_length=200)),
                ('deptTiming', models.CharField(max_length=10)),
                ('deptStation', models.CharField(max_length=100)),
                ('deptDate', models.CharField(max_length=20)),
                ('desTiming', models.CharField(max_length=10)),
                ('desStation', models.CharField(max_length=100)),
                ('desDate', models.CharField(max_length=20)),
            ],
        ),
    ]
